# Generated by Django 6.0.6 on 2026-09-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('SNACK', 'Snack'), ('DINNER', 'Dinner'), ('ANY', 'Any Meal')], default='ANY', max_length=20)),
                ('diet_type', models.CharField(choices=[('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('NON_VEGETARIAN', 'Non-Vegetarian'), ('EGGETARIAN', 'Eggetarian'), ('PESCATARIAN', 'Pescatarian')], default='VEGETARIAN', max_length=20)),
                ('calories', models.FloatField(default=200.0, help_text='Calories per serving (kcal)')),
                ('protein', models.FloatField(default=5.0, help_text='Protein (g)')),
                ('carbohydrates', models.FloatField(default=30.0, help_text='Carbohydrates (g)')),
                ('fat', models.FloatField(default=5.0, help_text='Fat (g)')),
                ('ingredients', models.JSONField(blank=True, default=list, help_text='List of primary ingredients')),
                ('cuisine', models.CharField(default='South Indian', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Keywords e.g. ["high-fiber", "low-calorie"]')),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['meal_type', 'diet_type'], name='nutrition_f_meal_ty_36410d_idx'), models.Index(fields=['cuisine'], name='nutrition_f_cuisine_f20782_idx')],
            },
        ),
    ]
