# Generated by Django 6.0.6 on 2026-09-05 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('scheduled_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_type', models.CharField(choices=[('TASK_REMINDER', 'Task Reminder'), ('HYDRATION', 'Hydration Reminder'), ('MEAL', 'Meal Reminder'), ('EXERCISE', 'Exercise Reminder'), ('MEDITATION', 'Meditation Reminder'), ('SLEEP', 'Sleep Wind-Down'), ('MISSED_TASK', 'Missed Task Alert'), ('RESCHEDULE', 'Schedule Recommendation'), ('WEEKLY_PROGRESS', 'Weekly Progress Report')], default='TASK_REMINDER', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'scheduled_time'], name='notificatio_user_id_2e47dd_idx')],
            },
        ),
    ]
