# Generated by Django 6.0.6 on 2026-09-05 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWellnessScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_score', models.FloatField(default=0.0, help_text='Overall Daily Wellness Score (0 to 100)')),
                ('task_adherence_score', models.FloatField(default=0.0, help_text='Max 25 points')),
                ('activity_score', models.FloatField(default=0.0, help_text='Max 25 points')),
                ('hydration_score', models.FloatField(default=0.0, help_text='Max 20 points')),
                ('sleep_score', models.FloatField(default=0.0, help_text='Max 20 points')),
                ('meditation_score', models.FloatField(default=0.0, help_text='Max 10 points')),
                ('summary_text', models.TextField(blank=True, default='')),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='analytics_d_user_id_750bc8_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
