# Generated by Django 6.0.6 on 2026-09-05 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('EXERCISE', 'Exercise & Physical Activity'), ('MEDITATION', 'Mindfulness & Meditation'), ('MEAL', 'Healthy Meal'), ('HYDRATION', 'Water Intake Reminder'), ('SLEEP_ROUTINE', 'Sleep Routine & Wind-down'), ('BREAK', 'Rest & Mobility Break'), ('CUSTOM', 'Custom Wellness Activity')], default='CUSTOM', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('scheduled_time', models.TimeField(help_text='Scheduled time of day (e.g. 07:30:00)')),
                ('duration', models.PositiveIntegerField(default=15, help_text='Duration in minutes')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('SKIPPED', 'Skipped'), ('RESCHEDULED', 'Rescheduled')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rescheduled_at', models.DateTimeField(blank=True, null=True)),
                ('original_time', models.TimeField(blank=True, help_text='Original scheduled time before rescheduling', null=True)),
                ('rescheduled_reason', models.TextField(blank=True, default='')),
                ('ai_explanation', models.TextField(blank=True, default='', help_text='Explainable AI rationale for this task')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(default='EXERCISE', max_length=30)),
                ('scheduled_time', models.TimeField()),
                ('actual_completion_time', models.TimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('skipped', models.BooleanField(default=False)),
                ('rescheduled', models.BooleanField(default=False)),
                ('day_of_week', models.IntegerField(default=0, help_text='0=Monday, 6=Sunday')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_records', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_logs', to='tasks.dailytask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dailytask',
            index=models.Index(fields=['user', 'date', 'status'], name='tasks_daily_user_id_fecc04_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytask',
            index=models.Index(fields=['user', 'scheduled_time'], name='tasks_daily_user_id_b58d61_idx'),
        ),
        migrations.AddIndex(
            model_name='behaviorrecord',
            index=models.Index(fields=['user', 'task_type', 'day_of_week'], name='tasks_behav_user_id_db6cd3_idx'),
        ),
    ]
