# Generated by Django 6.0.6 on 2026-09-05 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('FOOD', 'Food & Nutrition'), ('EXERCISE', 'Exercise & Movement'), ('MEDITATION', 'Mindfulness & Meditation'), ('ROUTINE', 'Daily Routine Plan'), ('RESCHEDULE', 'Adaptive Rescheduling')], default='FOOD', max_length=30)),
                ('title', models.CharField(default='Personalized Recommendation', max_length=255)),
                ('recommendation', models.JSONField(default=dict, help_text='Detailed payload of the recommendation')),
                ('explanation', models.TextField(blank=True, default='', help_text='Explainable AI rationale (Why this recommendation?)')),
                ('recommended_time', models.DateTimeField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'recommendation_type'], name='recommendat_user_id_b56fd8_idx')],
            },
        ),
    ]
