# Generated by Django 6.0.6 on 2026-09-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(choices=[('WALKING', 'Brisk Walking'), ('RUNNING', 'Running & Jogging'), ('YOGA', 'Yoga & Asanas'), ('STRETCHING', 'Stretching & Flexibility'), ('MOBILITY', 'Joint Mobility'), ('STRENGTH', 'Light Strength & Bodyweight'), ('BREATHING', 'Pranayama & Breathwork')], default='WALKING', max_length=30)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20)),
                ('duration', models.PositiveIntegerField(default=20, help_text='Standard duration in minutes')),
                ('equipment', models.CharField(choices=[('NONE', 'None (Bodyweight)'), ('YOGA_MAT', 'Yoga Mat'), ('DUMBBELLS', 'Light Dumbbells'), ('RESISTANCE_BAND', 'Resistance Band'), ('CHAIR', 'Chair')], default='NONE', max_length=30)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Keywords e.g. ["low-impact", "home-friendly"]')),
                ('instructions', models.TextField(blank=True, default='')),
                ('calories_burned_est', models.FloatField(default=80.0, help_text='Estimated calories burned')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'difficulty'], name='exercise_ex_categor_b77bbc_idx')],
            },
        ),
    ]
