# Generated by Django 6.0.6 on 2026-09-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeditationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('session_type', models.CharField(choices=[('BREATHING', 'Deep Breathing & Pranayama'), ('MINDFULNESS', 'Mindfulness Meditation'), ('RELAXATION', 'Stress Relief & Body Scan'), ('SLEEP_RELAXATION', 'Sleep Routine Relaxation'), ('SHORT_BREAK', 'Quick Micro-Break (3-5 mins)')], default='BREATHING', max_length=30)),
                ('duration', models.PositiveIntegerField(default=10, help_text='Duration in minutes')),
                ('description', models.TextField(blank=True, default='')),
                ('guide_steps', models.JSONField(blank=True, default=list, help_text='Step-by-step guidance instructions')),
                ('target_time_of_day', models.CharField(default='Anytime', help_text='e.g. Morning, Afternoon, Evening, Bedtime', max_length=50)),
            ],
            options={
                'ordering': ['duration', 'title'],
            },
        ),
    ]
