# Generated by Django 6.0.6 on 2026-09-05 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_exercises', models.JSONField(blank=True, default=list, help_text='e.g. ["Walking", "Yoga", "Stretching"]')),
                ('preferred_duration', models.PositiveIntegerField(default=30, help_text='Preferred duration in minutes (10, 20, 30, 45, 60)')),
                ('fitness_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_type', models.CharField(choices=[('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('NON_VEGETARIAN', 'Non-Vegetarian'), ('EGGETARIAN', 'Eggetarian'), ('PESCATARIAN', 'Pescatarian')], default='VEGETARIAN', max_length=30)),
                ('preferences', models.JSONField(blank=True, default=list, help_text='List of preferred food items/categories')),
                ('allergies', models.JSONField(blank=True, default=list, help_text='List of food allergies or intolerances')),
                ('cuisine', models.CharField(default='South Indian', help_text='Preferred cuisine, e.g. South Indian, North Indian, Continental', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=25)),
                ('height', models.FloatField(default=170.0, help_text='Height in centimeters')),
                ('weight', models.FloatField(default=65.0, help_text='Weight in kilograms')),
                ('activity_level', models.CharField(choices=[('SEDENTARY', 'Sedentary (Little or no exercise)'), ('LIGHTLY_ACTIVE', 'Lightly Active (Exercise 1-3 days/week)'), ('MODERATELY_ACTIVE', 'Moderately Active (Exercise 3-5 days/week)'), ('VERY_ACTIVE', 'Very Active (Hard exercise 6-7 days/week)')], default='MODERATELY_ACTIVE', max_length=30)),
                ('wake_time', models.TimeField(default='06:30:00')),
                ('sleep_time', models.TimeField(default='22:30:00')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('FITNESS', 'General Fitness'), ('HEALTHY_EATING', 'Healthy Eating'), ('BETTER_SLEEP', 'Better Sleep'), ('HYDRATION', 'Hydration'), ('MEDITATION', 'Mindfulness & Meditation'), ('PHYSICAL_ACTIVITY', 'Physical Activity')], max_length=30)),
                ('target', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0)),
                ('start_time', models.TimeField(default='07:00:00')),
                ('end_time', models.TimeField(default='22:00:00')),
                ('unavailable_periods', models.JSONField(blank=True, default=list, help_text='List of {"start": "09:00", "end": "16:00", "label": "College/Work"}')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('user', 'day')},
            },
        ),
    ]
