// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZgi0WzCSeZDzJtMqZawTO8i45oLvV_HQ',
    appId: '1:549793390584:web:028096c023ab094fd7400d',
    messagingSenderId: '549793390584',
    projectId: 'healthsync-ai-92d86',
    authDomain: 'healthsync-ai-92d86.firebaseapp.com',
    storageBucket: 'healthsync-ai-92d86.firebasestorage.app',
    measurementId: 'G-63JTK18XXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1XSFItBpQ_4APjon0wyrUJseHe_gkfIk',
    appId: '1:549793390584:android:9f2f86d63852cf0cd7400d',
    messagingSenderId: '549793390584',
    projectId: 'healthsync-ai-92d86',
    storageBucket: 'healthsync-ai-92d86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiZz2JbUK6tY0PlJ-rpYuNQn3JkBxIkk0',
    appId: '1:549793390584:ios:50731cd4a2fd8495d7400d',
    messagingSenderId: '549793390584',
    projectId: 'healthsync-ai-92d86',
    storageBucket: 'healthsync-ai-92d86.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiZz2JbUK6tY0PlJ-rpYuNQn3JkBxIkk0',
    appId: '1:549793390584:ios:50731cd4a2fd8495d7400d',
    messagingSenderId: '549793390584',
    projectId: 'healthsync-ai-92d86',
    storageBucket: 'healthsync-ai-92d86.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZgi0WzCSeZDzJtMqZawTO8i45oLvV_HQ',
    appId: '1:549793390584:web:174c508f433094dbd7400d',
    messagingSenderId: '549793390584',
    projectId: 'healthsync-ai-92d86',
    authDomain: 'healthsync-ai-92d86.firebaseapp.com',
    storageBucket: 'healthsync-ai-92d86.firebasestorage.app',
    measurementId: 'G-QGF7HXE1HW',
  );
}
