// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJj5SkZw2X3CHwkU1n0LKx_qTeg7LuUTQ',
    appId: '1:40562478940:web:e6b6b2419e47a4e832bb99',
    messagingSenderId: '40562478940',
    projectId: 'healthsyncai-847d9',
    authDomain: 'healthsyncai-847d9.firebaseapp.com',
    storageBucket: 'healthsyncai-847d9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm9PbLwEA-PN_OLcfaRLs7TO2BdziTzqs',
    appId: '1:40562478940:android:b01912f3d19d86dd32bb99',
    messagingSenderId: '40562478940',
    projectId: 'healthsyncai-847d9',
    storageBucket: 'healthsyncai-847d9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaeknxQ026eYHWxAKvenBM0pICld_49Vo',
    appId: '1:40562478940:ios:4b17d7e6adfb310232bb99',
    messagingSenderId: '40562478940',
    projectId: 'healthsyncai-847d9',
    storageBucket: 'healthsyncai-847d9.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaeknxQ026eYHWxAKvenBM0pICld_49Vo',
    appId: '1:40562478940:ios:4b17d7e6adfb310232bb99',
    messagingSenderId: '40562478940',
    projectId: 'healthsyncai-847d9',
    storageBucket: 'healthsyncai-847d9.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJj5SkZw2X3CHwkU1n0LKx_qTeg7LuUTQ',
    appId: '1:40562478940:web:28b0b3edd1dfc24e32bb99',
    messagingSenderId: '40562478940',
    projectId: 'healthsyncai-847d9',
    authDomain: 'healthsyncai-847d9.firebaseapp.com',
    storageBucket: 'healthsyncai-847d9.firebasestorage.app',
  );
}
